### ISSUE TITLE
upgrade for storybook 4.0.0

### ISSUE THREAD

**Issue by devhero** [usertech/neutrino-preset-react-storybook#1]
Hi,
could you update the package to work with storybook 4.0.0?
I've tried by myself without good results :-)

**Comment by brabeji** [comment]
@devhero Hello, 

I'm sorry, we currently need it only for v3 and I don't have much time on my hands.
What did you try?

**Comment by slikts** [comment]
I suppose that's is the reason for this issue:
```
{ Error: Cannot find module '@storybook/react/dist/server/config/webpack.config'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/mnt/c/work/chat-app/client/node_modules/@usertech/neutrino-preset-react-storybook/index.js:3:24)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3) code: 'MODULE_NOT_FOUND' }
```
Using `@storybook/react` 4.1.4.
